name: CD
on:
  workflow_call:
jobs:
  update-gitops:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gitops repo
        uses: actions/checkout@v7
        with:
          repository: ${{ vars.REPO_ORG }}/devboard-gitops
          token: ${{ secrets.GITOPS_REPO_PAT }}
          path: gitops
      - name: Install yq
        run: |
          sudo curl -sSL -o /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq
      - name: Bump backend + frontend image tags
        run: |
          cd gitops/devboard
          yq -i ".spec.template.spec.containers[0].image = \"${{ vars.DOCKERHUB_USERNAME }}/devboard-backend:${{ github.sha }}\"" rollout.yaml
          yq -i "(.spec.template.spec.containers[] | select(.name == \"devboard-frontend\") | .image) = \"${{ vars.DOCKERHUB_USERNAME }}/devboard-frontend:${{ github.sha }}\"" frontend-deployment.yaml
      - name: Commit deploy event
        run: |
          cd gitops
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "deploy: devboard@${{ github.sha }}" || echo "nothing to commit"
          git push
      - name: Push deploy metrics to Prometheus
        run: |
          NOW=$(date -u +%s)
          curl -sk --data "devboard_deploy_total 1" https://pushgateway.devboard.15-252-151-45.sslip.io/metrics/job/devboard_deploy/instance/${{ github.sha }}
        continue-on-error: true
